// <auto-generated />
using System;
using MDR.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MDR.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MDR.Domain.Devices.Mases2.Mas2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<double>("HumidityAlarmThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TempAlarmThreshold")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Mas2Device");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mases2.Mas2Data", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Mas2Data");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mouses2.Mouse2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AlarmThreshold")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mouse2");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mouses2.Mouse2Data", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<double>("Resistance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Mouse2Data");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mouses2B.Mouse2B", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AlarmThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("CableLength")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mouse2B");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mouses2B.Mouse2BData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<double>("LeakLocationPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Resistance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Mouse2BData");
                });

            modelBuilder.Entity("MDR.Domain.Devices.MousesCombo.MouseCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AlarmThreshold")
                        .HasColumnType("double precision");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MouseCombo");
                });

            modelBuilder.Entity("MDR.Domain.Devices.MousesCombo.MouseComboData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<double>("Resistance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("MouseComboData");
                });

            modelBuilder.Entity("MDR.Domain.Devices.MousesCombo.Reflectogram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("MouseComboDataId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MouseComboDataId");

                    b.ToTable("Reflectogram");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mases2.Mas2Data", b =>
                {
                    b.HasOne("MDR.Domain.Devices.Mases2.Mas2", "Device")
                        .WithMany("DeviceDatas")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mouses2.Mouse2Data", b =>
                {
                    b.HasOne("MDR.Domain.Devices.Mouses2.Mouse2", "Device")
                        .WithMany("DeviceDatas")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mouses2B.Mouse2BData", b =>
                {
                    b.HasOne("MDR.Domain.Devices.Mouses2B.Mouse2B", "Device")
                        .WithMany("DeviceDatas")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MDR.Domain.Devices.MousesCombo.MouseComboData", b =>
                {
                    b.HasOne("MDR.Domain.Devices.MousesCombo.MouseCombo", "Device")
                        .WithMany("DeviceDatas")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MDR.Domain.Devices.MousesCombo.Reflectogram", b =>
                {
                    b.HasOne("MDR.Domain.Devices.MousesCombo.MouseComboData", "MouseComboData")
                        .WithMany("Reflectograms")
                        .HasForeignKey("MouseComboDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MouseComboData");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mases2.Mas2", b =>
                {
                    b.Navigation("DeviceDatas");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mouses2.Mouse2", b =>
                {
                    b.Navigation("DeviceDatas");
                });

            modelBuilder.Entity("MDR.Domain.Devices.Mouses2B.Mouse2B", b =>
                {
                    b.Navigation("DeviceDatas");
                });

            modelBuilder.Entity("MDR.Domain.Devices.MousesCombo.MouseCombo", b =>
                {
                    b.Navigation("DeviceDatas");
                });

            modelBuilder.Entity("MDR.Domain.Devices.MousesCombo.MouseComboData", b =>
                {
                    b.Navigation("Reflectograms");
                });
#pragma warning restore 612, 618
        }
    }
}
